#version 460 core


layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;


uniform vec3 eyePos;
uniform mat4 inverseProjection;
uniform vec2 screenResolution;

struct ViewFrustum
{
    vec3 normal[4];
    float dist[4];
};

void ComputeViewFrustum(inout vec3 normal, inout float dist, vec3 point1, vec3 point2)
{
    vec3 dir1 = point1 - eyePos;
    vec3 dir2 = point2 - eyePos;

    // Normal to the plane(view frustum)
    normal = normalize(cross(dir1, dir2));

    // Distance to the origin, because normal is normalized
    dist = dot(normal, eyePos);
}


// Screen now divided into tiles(16 of them), every tile is subdivided into
// 4 points, this function convert them to view space.
vec3[4] ConvertScreenToViewCoordinates(const vec4 tilePointsScreen[4])
{
    vec3 tilePointsView[4];

    for(int i = 0; i < 4; ++i)
    {
        // Convert to NDC
        vec2 texCoord = tilePointsScreen[i].xy / screenResolution;

        // To clip
        vec4 clip = vec4(vec2(texCoord.x, 1.0 - texCoord.y) * 2.0 - 1.0, tilePointsScreen[i].z, tilePointsScreen[i].w);

        // Convert clip to view
        vec4 view = inverseProjection * clip;
        // Perspective divison
        view /= view.w;

        tilePointsView[i] = view.xyz;
    }

    return tilePointsView;
}


void main()
{
    uvec2 tileCoord = gl_GlobalInvocationID.xy;
    
    vec4 tilePointsScreen[4];
    // Points of current tile

    const uint blockSize = gl_WorkGroupSize.x;
    // top left
    //  TO CHECK -1 Z
    tilePointsScreen[0] = vec4(tileCoord * blockSize, 1.0, 1.0);
    // top right
    tilePointsScreen[1] = vec4(vec2((tileCoord.x + 1, tileCoord.y)) * blockSize, 1.0, 1.0);
    // bottom left
    tilePointsScreen[2] = vec4(vec2((tileCoord.x, tileCoord.y + 1))  * blockSize, 1.0, 1.0);
    // bottom right
    tilePointsScreen[3] = vec4(vec2((tileCoord.x + 1, tileCoord.y + 1)) * blockSize, 1.0, 1.0);


    vec3 tilePointsView[4] = ConvertScreenToViewCoordinates(tilePointsScreen);


    ViewFrustum viewFrustum;
    // left
    ComputeViewFrustum(viewFrustum.normal[0], viewFrustum.dist[0], tilePointsView[0], tilePointsView[2]);
    // right
    ComputeViewFrustum(viewFrustum.normal[1], viewFrustum.dist[1], tilePointsView[1], tilePointsView[3]);
    // top
    ComputeViewFrustum(viewFrustum.normal[2], viewFrustum.dist[2], tilePointsView[0], tilePointsView[1]);
    // bottom
    ComputeViewFrustum(viewFrustum.normal[3], viewFrustum.dist[3], tilePointsView[2], tilePointsView[3]);
}