#version 460 core

// 1024 threads
layout (local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

layout(std430, binding = 1) buffer vertices
{
    vec4 positions[];
};

uniform vec3 displacement;

void main()
{
    uint idx = gl_GlobalInvocationID.x;
    
    // placing back unvisible anymore particles
    if(positions[idx].y < 0.0)
        positions[idx].y = 75.0;

    positions[idx].xyz += displacement;
}